server:
  port: 9091

spring:
  application:
    name: short-url
  redis:
    database: 1
    host: 192.168.56.102
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        min-idle: 0
        max-wait: -1